# Generated by Django 5.2 on 2025-04-06 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_endereco'),
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data', models.DateTimeField()),
                ('local', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromissos_processos', to='clientes.cliente')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromissos_processos', to='processos.processo')),
            ],
        ),
    ]
